using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace DevicesEnStoringen
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        DatabaseConnectie conn = new DatabaseConnectie();

        public MainWindow()
        {
            InitializeComponent();
            grdStoringen.SetBinding(ItemsControl.ItemsSourceProperty, new Binding { Source = conn.ShowDataInGridView("SELECT StoringID AS ID, Beschrijving, Date(DatumToegevoegd) AS Datum, Prioriteit, Ernst, Status FROM Storing") });
            
            //grdStoringen.ItemsSource = conn.ShowDataInGridView("Select * From Student");
        }
        private void ChangeText(object sender, RoutedEventArgs e)
        {
           // DemoModel model = (sender as Button).DataContext as DemoModel;
            //model.DynamicText = (new Random().Next(0, 100).ToString());
        }

        private void grdStoringen_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var dgrd = sender as DataGrid;
            {
                var c = dgrd.Columns[0];
                dgrd.Columns.RemoveAt(0);
                dgrd.Columns.Add(c);
            }
        }

        private void beheer(object sender, RoutedEventArgs e)
        {
            DataRowView row = (DataRowView)grdStoringen.SelectedItems[0];
            MessageBox.Show(row["ID"].ToString());
        }
    }
}
