using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace DevicesEnStoringen
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class UCAlleDevices : UserControl
    {
        DatabaseConnectie conn = new DatabaseConnectie();
        public ObservableCollection<string> list = new ObservableCollection<string>();
        public UCAlleDevices()
        {
            InitializeComponent();
            grdDevices.SetBinding(ItemsControl.ItemsSourceProperty, new Binding { Source = conn.ShowDataInGridView("SELECT StoringID AS ID, Beschrijving, Date(DatumToegevoegd) AS Datum, Prioriteit, Ernst, Status FROM Storing") });

            //grdStoringen.ItemsSource = (IEnumerable)conn.ShowDataInGridView("SELECT StoringID AS ID, Beschrijving, Date(DatumToegevoegd) AS Datum, Prioriteit, Ernst, Status FROM Storing");

            list.Add("Alle storingen");
            list.Add("Open");
            list.Add("In behandeling");
            list.Add("Afgehandeld");
            lstType.ItemsSource = list;
        }

        private void grdStoringen_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var dgrd = sender as DataGrid;
            {
                var c = dgrd.Columns[0];
                dgrd.Columns.RemoveAt(0);
                dgrd.Columns.Add(c);
            }
        }

        private void RowButtonClick(object sender, RoutedEventArgs e)
        {
            DataRowView row = (DataRowView)grdDevices.SelectedItems[0];
            Button button = (Button)sender;

            if (button.Name == "btnBeheer")
            {
                Storing storing = new Storing(Convert.ToInt32(row["ID"]));
                storing.Show();
            }
            else if (button.Name == "btnVerwijder")
            {
                MessageBox.Show(button.Name);
            }
        }

        private void FilterDatagrid(object sender, EventArgs e)
        {
            if ((string)lstType.SelectedValue == "Alle storingen")
                grdDevices.SetBinding(ItemsControl.ItemsSourceProperty, new Binding { Source = conn.ShowDataInGridView("SELECT StoringID AS ID, Beschrijving, Date(DatumToegevoegd) AS Datum, Prioriteit, Ernst, Status FROM Storing WHERE Beschrijving LIKE '%" + txtZoek.Text + "%'") });
            else
                grdDevices.SetBinding(ItemsControl.ItemsSourceProperty, new Binding { Source = conn.ShowDataInGridView("SELECT StoringID AS ID, Beschrijving, Date(DatumToegevoegd) AS Datum, Prioriteit, Ernst, Status FROM Storing WHERE Beschrijving LIKE '%" + txtZoek.Text + "%' AND Status='" + lstType.SelectedItem + "'") });
        }

        private void btnRegistreerStoring_Click(object sender, RoutedEventArgs e)
        {
            Storing storing = new Storing();
            storing.Show();
        }
    }
}
